[phases.setup]
nixPkgs = [
    'php82',
    'php82Packages.composer',
    'php82Extensions.pdo',
    'php82Extensions.pdo_mysql',
    'php82Extensions.mbstring',
    'php82Extensions.xml',
    'php82Extensions.curl'
]

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
    'mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache',
    'php artisan config:cache',
    'php artisan route:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --class=OutfitFormulaSeeder --force && php artisan serve --host=0.0.0.0 --port=$PORT'
