[phases.setup]
nixPkgs = [
    'php82',
    'php82Packages.composer'
]

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
    'mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
