services:
  - type: web
    name: my-laravel-app
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    # 不在這裡設定環境變數，改成手動在 Render UI 設定

databases:
  - name: my-laravel-db
    region: singapore
    plan: free
    databaseName: outfit_formulas_db
    user: outfit_user
